name: Build .NET MAUI App Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    # Очистим кэш NuGet
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    # Шаг 1: Настроим .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.x

    # Шаг 2: Установим .NET MAUI
    - name: Install .NET MAUI
      run: dotnet workload install maui

    # Шаг 3: Добавляем источник DevExpress в NuGet с ключом
    - name: Register DevExpress Source
      run: dotnet nuget add source https://nuget.devexpress.com/api/v3/index.json -p ${{ secrets.DEVEXPRESS_NUGET_KEY }} -u DevExpress -n devexpress-nuget
        
    # Шаг 4: Восстановим зависимости
    - name: Restore dependencies
      run: dotnet restore

    # Шаг 5: Сборка проекта (без подписи)
    - name: Build
      run: |
        dotnet build MauiGithubActionsSample/MauiGithubActionsSample.csproj -c Release -f net9.0-android --no-restore

    # Шаг 6: Загружаем артефакты (APK или AAB файлы)
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
